In [39]:
# Raut, Shiska
# 1001_526_329
# 2023_02_26
# Assignment_01_01

import numpy as np

# returns a weight matrix for of size r X c + 1 (including bias) 
def get_weights_matrix(r, c, seed):
    
    np.random.seed(seed)
    weight_matrix = np.random.randn(r, c + 1)   # c + 1 for bias

    return weight_matrix

# given input 'x' and weight matrix 'W' return logsig(W*x) 
def get_layer_output(x, W):

    net_value = np.dot(W, x)
    activation_value = 1.0 / (1 + np.exp(-net_value))
    
    return activation_value

# cakculates mean squared error for a single sample
def get_mean_squared_error(y_sample, y_pred_sample):
    
    # get the numer of rows for output value
    n = y_sample.shape[0]
    
    # sum of squared error
    sse = np.sum(((y_sample - y_pred_sample)**2), axis = 1)
    
    # mean squared error
    mse = sse/n
    
    return mse

# calculates the average mse for results of a single epoch
def get_average_mse(Y, Y_pred):
    pass

# adjusts weights after a training sample has been processed
def adjust_weights(weights_list, x_train_sample, alpha, h):
    pass

# a single pass over the training data
def train_network(X_train,Y_train, alpha, h):
    pass

# get predictions for X_test after training
def get_predictions(weights_list, X_test):
    pass


def multi_layer_nn(X_train,Y_train,X_test,Y_test,layers,alpha,epochs,h=0.00001,seed=2):
    
    # get number of features and number of samples
    n_feat_train, n_train = X_train.shape
    __ , n_test = X_test.shape
    
    #get number of layers and initialize list to store weights for each layer
    n_layers = len(layers)
    weights_list = []
    
    # initalize list to store average MSE per epoch
    avg_mse_per_epoch = []
    
    # get weights for each layer
    for i in range(n_layers):
        
        if i == 0:
            # get weights for first layer
            weights_list.append(get_weights_matrix(layers[0], n_feat_train, seed))
        else:
            n_nodes = layers[i]
            n_input = layers[i - 1]
            weights_list.append(get_weights_matrix(n_nodes, n_input, seed))
    
    # do the following per epoch
    for i in range(epochs):
        weights_list = train_network(X_train,Y_train, alpha, h)
        Y_pred = get_predictions(weights_list, X_test)
        average_mse_per_epoch.append(get_average_mse(Y_test, Y_pred))
    # This function creates and trains a multi-layer neural Network
    # X_train: Array of input for training [input_dimensions,nof_train_samples]
    # Y_train: Array of desired outputs for training samnples [output_dimensions,nof_train_samples]
    # X_test: Array of input for testing [input_dimensions,nof_test_samples]
    # Y_test: Array of desired outputs for test samples [output_dimensions,nof_test_samples]
    # layers: array of integers representing number of nodes in each layer    
    # alpha: learning rate
    # epochs: number of epochs for training.
    # h: step size
    # seed: random number generator seed for initializing the weights.
    # return: This function should return a list containing 3 elements:
        # The first element of the return list should be a list of weight matrices.
        # Each element of the list corresponds to the weight matrix of the corresponding layer.

        # The second element should be a one dimensional array of numbers
        # representing the average mse error after each epoch. Each error should
        # be calculated by using the X_test array while the network is frozen.
        # This means that the weights should not be adjusted while calculating the error.

        # The third element should be a two-dimensional array [output_dimensions,nof_test_samples]
        # representing the actual output of network when X_test is used as input.

    # Notes:
    # DO NOT use any other package other than numpy
    # Bias should be included in the weight matrix in the first column.
    # Assume that the activation functions for all the layers are sigmoid.
    # Use MSE to calculate error.
    # Use gradient descent for adjusting the weights.
    # use centered difference approximation to calculate partial derivatives.
    # (f(x + h)-f(x - h))/2*h
    # Reseed the random number generator when initializing weights for each layer.
    # i.e., Initialize the weights for each layer by:
    # np.random.seed(seed)
    # np.random.randn()
    pass

In [40]:
def sigmoid(x):
    # This function calculates the sigmoid function
    # x: input
    # return: sigmoid(x)
    # Your code goes here
    return 1/(1+np.exp(-x))

def create_toy_data_nonlinear(n_samples=1000):
    X = np.zeros((n_samples, 4))
    X[:, 0] = np.linspace(-1, 1, n_samples)
    X[:, 1] = np.linspace(-1, 1, n_samples)
    X[:, 2] = np.linspace(-1, 1, n_samples)
    X[:, 3] = np.linspace(-1, 1, n_samples)

    y = X[:, 0]**2 + 2*X[:, 1]  - 0.5*X[:, 2] + X[:, 3]**3 + 0.3

    # shuffle X and y
    idx = np.arange(n_samples)
    np.random.shuffle(idx)
    X = X[idx]
    y = y[idx]

    return X, y

def create_toy_data_nonlinear_2d(n_samples=1000):
    X = np.zeros((n_samples, 4))
    X[:, 0] = np.linspace(-1, 1, n_samples)
    X[:, 1] = np.linspace(-1, 1, n_samples)
    X[:, 2] = np.linspace(-1, 1, n_samples)
    X[:, 3] = np.linspace(-1, 1, n_samples)
    y = np.zeros((n_samples, 2))
    y[:, 0] = 0.5*X[:, 0] -0.2 * X[:, 1]**2 - 0.2*X[:, 2] + X[:, 3]*X[:,1] - 0.1
    y[:, 1] = 1.5 * X[:, 0] + 1.25 * X[:, 1]*X[:, 0] + 0.4 * X[:, 2] * X[:, 0]

    # shuffle X and y
    idx = np.arange(n_samples)
    np.random.shuffle(idx)
    X = X[idx]
    y = y[idx]

    return X, y

def test_can_fit_data_test():
    np.random.seed(12345)
    from sklearn.model_selection import train_test_split
    X, y = create_toy_data_nonlinear(n_samples=110)
    y = sigmoid(y)
    X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.1, random_state=42)
    Y_train = Y_train.reshape(-1,1)
    Y_train = Y_train
    Y_test = Y_test.reshape(-1,1)
    Y_test = Y_test

    multi_layer_nn(X_train,Y_train,X_test,Y_test,[2,1],alpha=0.35,epochs=1000,h=1e-8,seed=1234)
    
    return 0

test_can_fit_data_test()



[[0.04125537]
 [0.99982438]]


0

In [2]:
import numpy as np
x = np.array([1,2,3,4,5,6,7])
x[1::]

array([2, 3, 4, 5, 6, 7])

In [5]:
np.random.seed(22)
np.random.randn(3,3)

array([[-0.09194992, -1.46335065,  1.08179168],
       [-0.23932517, -0.49112914, -1.00227201],
       [ 0.9188215 , -1.1036321 ,  0.62649346]])

In [24]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
x = np.random.randn(5,1)
y = np.random.randn(4,1)

In [10]:
x

array([[-0.2821113 ],
       [-0.06322892],
       [-1.53699059],
       [ 0.2917757 ],
       [ 2.23383417]])

In [9]:
y

array([[ 1.44043622],
       [ 0.02830434],
       [-1.48941825],
       [ 0.22179747]])

In [11]:
x[1::] = y

In [13]:
x.shape

(5, 1)

In [14]:
def get_layer_output(x, W):

    net_value = np.dot(W, x)
    activation_value = 1.0 / (1 + np.exp(-net_value))
    
    return activation_value

# given sample 'x_sample' and list of all weights in the network 'weights_list', 
# returns network output y_sample
def get_network_output(x_sample, weights_list):

    nn_input = np.zeros((x_sample.shape[0]+1, 1))
    nn_input[1::] = x_sample

    for i in range(weights_list):
        W = weights_list[i]
        layer_output = get_layer_output(nn_input, W)
        next_layer_input = np.zeros((layer_output.shape[0]+1, 1))
        next_layer_input[1::] = layer_output
    
    return layer_output

In [17]:
W_l1 = np.array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873],     
 [ 0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495]], ndmin = 2)
W_l2 = np.array([[ 0.47143516, -1.19097569,  1.43270697]], ndmin = 2)

In [23]:
X = np.array([1, 0.9266055, 0.9266055, 0.9266055, 0.9266055], ndmin = 2)
X = np.transpose(X)

In [24]:
X.shape

(5, 1)

In [33]:
np.dot(W_l1, X)

array([[-0.26198176],
       [-0.96968375]])

In [34]:
1.0 / (1 + np.exp(-np.dot(W_l1, X)))

array([[0.43487661],
       [0.27494354]])

In [36]:
X2 = np.array([[1.0],[0.43487661],[0.27494354]], ndmin = 2)

In [37]:
X2

array([[1.        ],
       [0.43487661],
       [0.27494354]])

In [38]:
np.dot(W_l2, X2)

array([[0.34742122]])

In [39]:
1.0 / (1 + np.exp(-np.dot(W_l2, X2)))

array([[0.58599209]])

In [41]:
temp_list = [[1, 2, 3], ['a' 'b']]

In [50]:
temp_list

[array([[1.       ],
        [0.9266055],
        [0.9266055],
        [0.9266055],
        [0.9266055]]),
 array([[1.        ],
        [0.43487661],
        [0.27494354]])]

In [105]:
temp_list = [X, X2]

In [106]:
m = temp_list[0]
m[0] = 500

In [107]:
temp_list

[array([[500.       ],
        [  0.9266055],
        [  0.9266055],
        [  0.9266055],
        [  0.9266055]]),
 array([[1.        ],
        [0.43487661],
        [0.27494354]])]

In [61]:
orig_val = temp_list[0][0].copy()
orig_val

array([0.])

In [62]:
temp_list[0][0] = 90

In [67]:
a = 90000

In [76]:
a = temp_list[0][0]

In [77]:
a = 605

In [79]:
ad_t = temp_list

In [81]:
ad_t[0][0] = 45

In [82]:
temp_list

[array([[45.       ],
        [ 0.9266055],
        [ 0.9266055],
        [ 0.9266055],
        [ 0.9266055]]),
 array([[1.        ],
        [0.43487661],
        [0.27494354]])]

In [83]:
temp_mat_1 = temp_list[0]

In [84]:
temp_mat_1[0,0] = 800

In [96]:
mymat = np.random.rand(2,3)

In [97]:
mylist = []
mylist.append(mymat)

In [98]:
mylist

[array([[0.96681378, 0.53878032, 0.55327257],
        [0.19281462, 0.20460739, 0.32305099]])]

In [99]:
mymat[0][0] = 0.29

In [100]:
mymat

array([[0.29      , 0.53878032, 0.55327257],
       [0.19281462, 0.20460739, 0.32305099]])

In [101]:
mylist

[array([[0.29      , 0.53878032, 0.55327257],
        [0.19281462, 0.20460739, 0.32305099]])]

In [103]:
mymat = np.random.rand(9,3)

In [104]:
mylist

[array([[0.29      , 0.53878032, 0.55327257],
        [0.19281462, 0.20460739, 0.32305099]])]