In [66]:
import numpy as np

In [67]:
w1 = np.array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873],     
 [ 0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495]], ndmin = 2)
w2 = np.array([[ 0.47143516, -1.19097569,  1.43270697]], ndmin = 2)

In [68]:
x1 = np.array([[1],
       [0.1559633],
       [0.1559633],
       [0.1559633],
       [0.1559633]], ndmin = 2)

In [69]:
x1.shape

(5, 1)

In [70]:
y1 = np.array([[0.70548121]], ndmin = 2)

In [71]:
y1.shape

(1, 1)

In [72]:
net1 = np.dot(w1, x1)
net1

array([[0.34798875],
       [0.57462439]])

In [73]:
a1 = 1.0 / (1 + np.exp(-net1))
a1

array([[0.58612977],
       [0.63982954]])

In [74]:
a1 = np.array([[1],
       [0.58612977],
       [0.63982954]]
       , ndmin = 2)

In [75]:
net2 = np.dot(w2, a1)
net2

array([[0.69005709]])

In [76]:
a2 = 1.0 / (1 + np.exp(-net2))
a2

array([[0.66597963]])

In [77]:
y_target = 0.6369298

In [78]:
mse = np.sum(((y_target - a2)**2), axis = 1) / 1
mse

array([0.00084389])

In [25]:
1.0 / (1 + np.exp(-np.dot(w2, X2)))

array([[0.58599209]])

In [80]:
gradient = (0.0008438924306198816 + 0.0008438925052988561) / (2*1e-8)
gradient

84389.2467959369

In [32]:
temp_list

[array([[ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873],
        [ 0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495]]),
 array([[ 0.47143516, -1.19097569,  1.43270697]])]

In [28]:
m = temp_list[0][0,0]
m[0] = 500

[array([[500.       ],
        [  0.9266055],
        [  0.9266055],
        [  0.9266055],
        [  0.9266055]]),
 array([[1.        ],
        [0.43487661],
        [0.27494354]])]

In [61]:
orig_val = temp_list[0][0].copy()
orig_val

array([0.])

In [62]:
temp_list[0][0] = 90

In [67]:
a = 90000

In [76]:
a = temp_list[0][0]

In [77]:
a = 605

In [79]:
ad_t = temp_list

In [81]:
ad_t[0][0] = 45

In [82]:
temp_list

[array([[45.       ],
        [ 0.9266055],
        [ 0.9266055],
        [ 0.9266055],
        [ 0.9266055]]),
 array([[1.        ],
        [0.43487661],
        [0.27494354]])]

In [83]:
temp_mat_1 = temp_list[0]

In [84]:
temp_mat_1[0,0] = 800

In [96]:
mymat = np.random.rand(2,3)

In [97]:
mylist = []
mylist.append(mymat)

In [98]:
mylist

[array([[0.96681378, 0.53878032, 0.55327257],
        [0.19281462, 0.20460739, 0.32305099]])]

In [99]:
mymat[0][0] = 0.29

In [100]:
mymat

array([[0.29      , 0.53878032, 0.55327257],
       [0.19281462, 0.20460739, 0.32305099]])

In [101]:
mylist

[array([[0.29      , 0.53878032, 0.55327257],
        [0.19281462, 0.20460739, 0.32305099]])]

In [103]:
mymat = np.random.rand(9,3)

In [104]:
mylist

[array([[0.29      , 0.53878032, 0.55327257],
        [0.19281462, 0.20460739, 0.32305099]])]

In [ ]:
[[-0.00373395, -0.00058236, -0.00058236, -0.00058236, -0.00058236], 
       [ 0.00426714,  0.00066552,  0.00066552,  0.00066552,  0.00066552]])
-0.0037339487242177977
0.0006655175651022749

In [81]:
abs(0.005176511931781274- 0.10182781417045624)

0.09665130223867496